name: terapievim
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.1.0+1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  firebase_crashlytics: ^3.0.11
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.17
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.17
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  url_launcher: ^6.1.8
  vexana: ^3.3.2
  fluttertoast: ^8.1.2
  image_picker: ^0.8.6+1
  video_player: ^2.5.1
  permission_handler: ^10.2.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3 # flutter pub  run build_runner watch

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700