name: terapievim
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  animated_bottom_navigation_bar: ^1.1.0+1
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  firebase_storage: ^11.0.16
  firebase_crashlytics: ^3.0.17
  connectivity_plus: ^2.3.5
  shared_preferences: ^2.0.20
  flutter_secure_storage: ^8.0.0
  equatable: ^2.0.5
  flutter_native_splash: ^2.2.19
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  url_launcher: ^6.1.10
  vexana: ^3.4.1
  fluttertoast: ^8.2.1
  image_picker: ^0.8.7
  video_player: ^2.6.0
  permission_handler: ^10.2.0
  intl: ^0.17.0
  videosdk: ^1.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3 # flutter pub  run build_runner watch
  very_good_analysis: ^4.0.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700